import './ActionSheet';
import './AddAndSubtract';
import './Alert';
import './Badge';
import './Btn';
import './CardView';
import './Confirm';
import './Dialog';
import './Drop';
import './DynamicText';
import './HeaderedSheet';
import './ImgHolder';
import './ImgPicker';
import './ImgRollView';
import './KeyboardAdaptiveView';
import './Loading';
import './NavBar';
import './NumericKeyboard';
import './Overlay';
import './PhoneNumInput';
import './Progress';
import './RefreshView';
import './Sheet';
import './SmsCaptchaInput';
import './TabBar';
import './ToolTip';
import './TransPxToDp';
import './Validator';
import './VirtualPasswordInput';


// 首页放最后，确保已经获取了所有页面
import './Home';
